"use client";

import { useEffect, useState } from "react";
import { api } from "../lib/client";
import { Brand, EmptyState, formatDate, LoadingCard, StatusBadge } from "./asar-ui";
import { telegramHaptic } from "../lib/telegram";

type Managed = { id: string; participantName: string; contactValue: string; quantity: number; comment: string; status: string; requirementTitle: string; asar: { title: string; startsAt: string; publicLocation: string; exactAddress?: string; lifecycleStatus: string } };
export function ManageCommitment({ token }: { token: string }) {
  const [item, setItem] = useState<Managed | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [toast, setToast] = useState("");
  useEffect(() => { api<{ commitment: Managed }>(`/api/public/commitments/${token}`).then((data) => setItem(data.commitment)).catch((caught) => setError(caught instanceof Error ? caught.message : "Ссылка недоступна")).finally(() => setLoading(false)); }, [token]);
  const act = async (action: string) => { setBusy(true); setError(""); try { const data = await api<{ commitment: Managed }>(`/api/public/commitments/${token}`, { method: "POST", body: JSON.stringify({ action }) }); telegramHaptic(action === "confirm" ? "success" : "light"); setItem(data.commitment); setToast(action === "confirm" ? "Участие подтверждено" : "Участие отменено — инициатор увидит риск сразу"); setTimeout(() => setToast(""), 3500); } catch (caught) { telegramHaptic("error"); setError(caught instanceof Error ? caught.message : "Не удалось обновить участие"); } finally { setBusy(false); } };
  if (loading) return <div className="guest-page"><div className="guest-shell"><div className="guest-top"><Brand compact /></div><LoadingCard /></div></div>;
  if (!item) return <div className="guest-page"><div className="guest-shell"><div className="guest-top"><Brand compact /></div><EmptyState title="Ссылка недоступна" text={error} /></div></div>;
  return <div className="guest-page"><div className="guest-shell"><div className="guest-top"><Brand compact /><small>Личная ссылка участника</small></div><section className="manage-card"><StatusBadge state={item.status} /><h1>{item.asar.title}</h1><p className="panel-lead">{item.participantName}, вы взяли ответственность за «{item.requirementTitle}».</p>{error && <div className="error-banner">{error}</div>}<div className="manage-facts"><div><small>Когда</small><strong>{formatDate(item.asar.startsAt, true)}</strong></div><div><small>Где</small><strong>{item.asar.publicLocation}</strong></div><div><small>Ваш вклад</small><strong>{item.requirementTitle} · {item.quantity}</strong></div><div><small>Контакт</small><strong>{item.contactValue}</strong></div></div>
    {item.asar.exactAddress ? <div className="exact-address"><strong>Точный адрес:</strong> {item.asar.exactAddress}</div> : item.status === "CLAIMED" && <div className="error-banner">Точный адрес откроется после подтверждения участия.</div>}
    {item.status === "CLAIMED" && <button className="button button-success button-large button-block" disabled={busy} onClick={() => act("confirm")}>{busy ? "Подтверждаем…" : "Подтвердить участие"}</button>}{["CLAIMED", "CONFIRMED"].includes(item.status) && <button className="button button-plain button-block danger-text" disabled={busy} style={{ marginTop: 10 }} onClick={() => act("cancel")}>Не смогу участвовать</button>}{item.status === "CONFIRMED" && <div className="success-banner">Спасибо — ваше подтверждение теперь учитывается в фактической готовности асара.</div>}{item.status === "CANCELLED" && <div className="error-banner">Вы отменили участие. Критическая роль, если это была она, уже снова открыта для набора.</div>}
  </section>{toast && <div className="toast">{toast}</div>}</div></div>;
}
